version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table containing Airbnb listings.
    columns:
      - name: listing_id
        description: Primary key for the listing.
        tests:
          - unique
          - not_null

      - name: host_id
        description: The host's id, referencing the host table.
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: Type of the apartment/room.
        tests:
          - accepted_values:
              values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']

      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        tests:
          - positive_value

  - name: dim_hosts_cleansed
    description: Cleansed table of the Airbnb hosts.
    columns:
      - name: HOST_ID
        description: The host's id, referencing the host table. This is the primary key
        tests: 
          - not_null
          - unique
      
      - name: HOST_NAME
        description: Name of host.
        tests:
          - not_null
      
      - name: IS_SUPERHOST
        description: Defines whether the host is a superhost.
        tests: 
          - accepted_values:
             values: ['t', 'f']

  - name: dim_listings_w_hosts
    tests:
      - dbt_expectations.expect_table_column_count_to_equal_other_table:
          compare_model: source('airbnb', 'listings')

  - name: fct_reviews
    columns:
      - name: listing_id
        tests:
          - relationships:
              to: ref('dim_listings_cleansed')
              field: listing_id
      - name: reviewer_name
        tests:
          - not_null
      
      - name: review_sentiment
        tests:
          - accepted_values:
              values: ['positive', 'neutral', 'negative']
